apiVersion: apps/v1
kind: Deployment
metadata:
  name: file-server-ui
  namespace: pechka
  labels:
    app: file-server-ui
spec:
  selector:
    matchLabels:
      app: file-server-ui
  template:
    metadata:
      labels:
        app: file-server-ui
    spec:
      containers:
        - name: file-server-ui
          image: ghcr.io/k-wa-wa/pechka-file-server-ui
          ports:
            - containerPort: 3000
          command: [
            "/bin/bash", "-c",
            "API_URL=http://file-server-api.pechka.svc.cluster.local:8000 node server.js"
          ]
          resources:
            requests:
              cpu: 100m
              memory: 256Mi
            limits:
              cpu: 500m
              memory: 512Mi
          env:
            - name: API_URL
              value: http://file-server-api.pechka.svc.cluster.local:8000
          # readinessProbe:
          #   httpGet:
          #     path: /
          #     port: 3000
          #   initialDelaySeconds: 20
          #   timeoutSeconds: 20
---
apiVersion: autoscaling/v2
kind: HorizontalPodAutoscaler
metadata:
  name: file-server-ui
  namespace: pechka
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: file-server-ui
  minReplicas: 2
  maxReplicas: 5
  metrics:
  - type: Resource
    resource:
      name: cpu
      target:
        type: Utilization
        averageUtilization: 70
---
apiVersion: v1
kind: Service
metadata:
  name: file-server-ui
  namespace: pechka
spec:
  selector:
    app: file-server-ui
  type: ClusterIP
  ports:
    - protocol: TCP
      port: 80
      targetPort: 3000
